workflows:
  android-build-jdk11:
    name: Android Build (JDK 11 Compatible)
    instance_type: mac_mini_m2

    environment:
      flutter: 2.0.1
      java: 11

    triggering:
      events:
        - push

    scripts:

      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Build Android AppBundle
        script: |
          flutter build appbundle --release

    artifacts:
      - build/app/outputs/apk/**/*.apk
